### ISSUE TITLE
Error building the 7.10 box?

### ISSUE THREAD

**Issue by LambdaLord** [ynniv/opengenera#13]
I'm really happy that this project exists, but I'd be even happier if I could demo the power of Genera to my friends, and make them quit wondering why I'm so obsessed with LispM's. 

Relevant Error message below.

try: sudo gem install veewee
make[1]: Leaving directory '~/vlispm/opengenera-master'
==> box: Adding box 'opengenera' (v0) for provider: 
    box: Downloading: ubuntu-7.10-server-amd64.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file ~/vlispm/opengenera-master/ubuntu-7.10-server-amd64.box
Makefile:39: recipe for target 'opengenera-box' failed
make: **\* [opengenera-box] Error 1

This happened on the latest Arch Linux release. I've double checked all my dependencies so I'm at a loss right now. Thank in advance for any help you can provide.

**Comment by ynniv** [comment]
It should only print this if the veewee command is not available. Have you tried "sudo gem install veewee"?
