### ISSUE TITLE
opengenera.tar.bz2 disappeared from the world wide web

### ISSUE THREAD

**Issue by ludns** [ynniv/opengenera#18]
It's pretty much impossible to find a mirror of the file on the internet nowadays. Even the torrent disappeared. If someone is kind enough to send me the file by email (justin@glibert.io) I would greatly appreciate

**Comment by TheFausap** [comment]
There's a snap4.tar.gz on unlambda.com

From reddit:
<https://news.ycombinator.com/vote?id=9072265&how=up&goto=item%3Fid%3D9062088>
typedweb <https://news.ycombinator.com/user?id=typedweb> on Feb 19, 2015
<https://news.ycombinator.com/item?id=9072265> [-]

http://www.unlambda.com/download/genera/snap4.tar.gz

Here's some instructions on setting it up:

http://www.cliki.net/VLM_on_Linux


I don't know if this file is useful.


regards,

fausto


Il giorno dom 28 ott 2018 alle ore 11:51 Justin Glibert <
notifications@github.com> ha scritto:

**Comment by ludns** [comment]
Hi Fausto,

Thank you for your help. From the instructions:
"You also want the OpenGenera 2.0 distribution tarball which includes the system sources as well as 
additional software packages and example files. There is no official distribution site for this tar ball, so 
you will have to ask around for this. If you have it, unpack it in a directory that you wish to be accessed 
by the VLM, for example /vlm."

That Tarball is the file I am looking for. Do you have Genera running on your computer?

Thanks,
Justin

**Comment by TheFausap** [comment]
Hi justin,

I find another site : https://static.loomcom.com/genera/genera-install.html

where you can find also a var_lib tar archive. With the setup described in
that site, there's no need of opengenera.tar.bz2, if I understood well

regards,
Fausto

Il giorno dom 28 ott 2018 alle ore 12:21 Justin Glibert <
notifications@github.com> ha scritto:

**Comment by ludns** [comment]
I can confirm that following the instructions on this link [https://static.loomcom.com/genera/genera-install.html](https://static.loomcom.com/genera/genera-install.html) works perfectly. I just had to do a chmod 777 on the symbolic folder to fix a write error when saving the world in Genera

Thanks Fausto!
